#!/bin/bash

# QUICK BACKEND DEPLOYMENT TO RENDER
# This script helps you deploy the backend to Render.com in minutes

echo "🚀 Tutor AI Backend Deployment Guide"
echo "======================================"
echo ""
echo "Your Frontend is already deployed at:"
echo "📱 https://ai-tutor-94ff4.web.app"
echo ""
echo "Now deploy the backend to make it fully functional!"
echo ""
echo "STEP 1: Prepare for Deployment"
echo "================================"
echo ""
echo "1a. Add production dependencies to requirements.txt:"
echo "    pip install gunicorn"
echo "    pip freeze > requirements.txt"
echo ""
echo "1b. Commit and push to GitHub:"
echo "    git add ."
echo "    git commit -m 'Add Procfile and gunicorn for production'"
echo "    git push origin main"
echo ""
echo "STEP 2: Create Render Account"
echo "=============================="
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Grant access to your Tutor-ai-antigravity repository"
echo ""
echo "STEP 3: Deploy Backend"
echo "======================"
echo "1. In Render Dashboard, click '+ New' → 'Web Service'"
echo "2. Select your 'Tutor-ai-antigravity' repository"
echo "3. Fill in these settings:"
echo "   - Name: tutor-ai-backend"
echo "   - Environment: Python 3.11"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: gunicorn --workers 2 --timeout 120 app:app"
echo "   - Plan: Free"
echo ""
echo "STEP 4: Add Environment Variables"
echo "=================================="
echo "In Render Dashboard → Settings → Environment:"
echo ""
echo "Add these variables:"
echo "  GEMINI_API_KEY = your_actual_gemini_api_key"
echo "  FLASK_ENV = production"
echo "  DEBUG = false"
echo ""
echo "Get GEMINI_API_KEY from: https://ai.google.dev"
echo ""
echo "STEP 5: Complete Deployment"
echo "============================"
echo "1. Click 'Deploy' button in Render"
echo "2. Wait for build to complete (2-3 minutes)"
echo "3. You'll get a URL like: https://tutor-ai-backend.onrender.com"
echo ""
echo "STEP 6: Update Frontend & Redeploy"
echo "===================================="
echo "1. Edit: frontend/src/services/api.js"
echo "2. Change the backend URL:"
echo "   return 'https://tutor-ai-backend.onrender.com/api';"
echo ""
echo "3. Rebuild and deploy:"
echo "   cd frontend && npm run build && cd .."
echo "   firebase deploy --only hosting"
echo ""
echo "STEP 7: Test Everything"
echo "========================"
echo "1. Open: https://ai-tutor-94ff4.web.app"
echo "2. Create account or login"
echo "3. Check DevTools (F12) → Network tab"
echo "4. Try a feature that requires the backend"
echo "5. Verify API calls succeed (green responses)"
echo ""
echo "✅ You're Done!"
echo "==============="
echo "Frontend:  https://ai-tutor-94ff4.web.app"
echo "Backend:   https://tutor-ai-backend.onrender.com"
echo ""
echo "For issues, see BACKEND_DEPLOYMENT.md"
